gateway:
  replicaCount: 2
  image:
    repository: jhtyl13r/jenkins-gateway
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 31300

order:
  replicaCount: 2
  image:
    repository: jhtyl13r/jenkins-orders
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 31400

user:
  replicaCount: 1
  image:
    repository: jhtyl13r/jenkins-users
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
