apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: {{ .Values.order.service.type }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.service.targetPort }}
      nodePort: {{ .Values.order.service.nodePort }}
      protocol: TCP
  selector:
    app: order-deployment