gateway:
  replicaCount: 1
  image:
    repository: jhtyl13r/jenkins-gateway
    tag: latest
    pullPolicy: Always
  imagePullSecrets:
    - name: regcred
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 31100

order:
  replicaCount: 1
  image:
    repository: jhtyl13r/jenkins-orders
    tag: latest
    pullPolicy: Always
  imagePullSecrets:
    - name: regcred
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 31200

user:
  replicaCount: 1
  image:
    repository: jhtyl13r/jenkins-users
    tag: latest
    pullPolicy: Always
  imagePullSecrets:
    - name: regcred
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
