apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-deployment
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-deployment
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
          imagePullPolicy: {{ .Values.order.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.order.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
