apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: {{ .Values.user.service.type }}
  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: {{ .Values.user.service.targetPort }}
      protocol: TCP
  selector:
    app: user-deployment